# Generated by Django 3.2.5 on 2021-10-26 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_image', models.URLField(blank=True)),
                ('welcome_text', models.CharField(max_length=150)),
                ('facebook', models.URLField(blank=True)),
                ('linkliden', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('dribble', models.URLField(blank=True)),
                ('resume', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link_name', models.CharField(max_length=20)),
                ('social_link', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='main.mainfolio')),
            ],
        ),
    ]
