# Generated by Django 3.2.5 on 2021-10-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfolio',
            name='dribble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainfolio',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainfolio',
            name='linkliden',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainfolio',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainfolio',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
