# Generated by Django 3.2.5 on 2021-10-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211026_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfolio',
            name='welcome_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainfolio',
            name='welcome_text',
            field=models.CharField(max_length=150),
        ),
    ]
