# Generated by Django 3.2.5 on 2021-10-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211026_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfolio',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
