# Generated by Django 3.2.5 on 2021-10-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectfolio_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfolio',
            name='project_image',
            field=models.URLField(blank=True, default='https://libum.vercel.app/assets/linktree-features-analytics.webp', null=True),
        ),
        migrations.AlterField(
            model_name='projectfolio',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
